name: Database Bootstrap

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment to deploy'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
      schema_name:
        description: "Schema name"
        required: false
        type: string
      sql_directory:
        description: "Schema name"
        required: false
        type: string  
jobs:
  bootstrap:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure AWS credentials
        run: |
          echo "Welcome to the Database Bootstrap workflow!"
      
